### ISSUE TITLE
frequent problems uploading on OS X with ch430 serial driver

### ISSUE THREAD

**Issue by jasonblewis** [kmpm/nodemcu-uploader#61]
On OSX, uploading fails about 4/5 times I try. Typical session attached below.

Using nodemcu-uploader 0.3.2 (serial 2.7) and the ch430 serial usb chip and driver on a wemos device.

Tested with 2 different wemos devices with same result.

```
jason@tolkien:~/Dropbox/projects/nodemculedchaser$ nodemcu-uploader --port /dev/tty.wchusbserial1420 --start_baud 115200 --baud 115200 upload init.lua
opening port /dev/tty.wchusbserial1420 with 115200 baud
Preparing esp for transfer.
Transferring init.lua as init.lua
All done!
jason@tolkien:~/Dropbox/projects/nodemculedchaser$ nodemcu-uploader --port /dev/tty.wchusbserial1420 --start_baud 115200 --baud 115200 upload init.lua
opening port /dev/tty.wchusbserial1420 with 115200 baud
Traceback (most recent call last):
  File "/usr/local/bin/nodemcu-uploader", line 11, in <module>
    sys.exit(main_func())
  File "/usr/local/lib/python2.7/site-packages/nodemcu_uploader/main.py", line 250, in main_func
    uploader = Uploader(args.port, args.baud, start_baud=args.start_baud)
  File "/usr/local/lib/python2.7/site-packages/nodemcu_uploader/uploader.py", line 68, in __init__
    __sync()
  File "/usr/local/lib/python2.7/site-packages/nodemcu_uploader/uploader.py", line 66, in __sync
    raise DeviceNotFoundException('Device not found or wrong port')
nodemcu_uploader.exceptions.DeviceNotFoundException: Device not found or wrong port
jason@tolkien:~/Dropbox/projects/nodemculedchaser$ nodemcu-uploader --port /dev/tty.wchusbserial1420 --start_baud 115200 --baud 115200 upload init.lua
opening port /dev/tty.wchusbserial1420 with 115200 baud
Preparing esp for transfer.
error when preparing "function recv_name(d) d=d:gsub('%z.*','') file.remove(d) file.open(d,'w') uart.on('data',130,recv_block,0) uart.write(0,'\006') end
stdin:15: '=' expected near 'function'
> "
Traceback (most recent call last):
  File "/usr/local/bin/nodemcu-uploader", line 11, in <module>
    sys.exit(main_func())
  File "/usr/local/lib/python2.7/site-packages/nodemcu_uploader/main.py", line 258, in main_func
    args.restart)
  File "/usr/local/lib/python2.7/site-packages/nodemcu_uploader/main.py", line 64, in operation_upload
    raise Exception('Error preparing nodemcu for reception')
Exception: Error preparing nodemcu for reception
jason@tolkien:~/Dropbox/projects/nodemculedchaser$ nodemcu-uploader --port /dev/tty.wchusbserial1420 --start_baud 115200 --baud 115200 upload init.lua
opening port /dev/tty.wchusbserial1420 with 115200 baud
Preparing esp for transfer.
error when preparing "e
stdin:7: '=' expected near 'e'
> "
Traceback (most recent call last):
  File "/usr/local/bin/nodemcu-uploader", line 11, in <module>
    sys.exit(main_func())
  File "/usr/local/lib/python2.7/site-packages/nodemcu_uploader/main.py", line 258, in main_func
    args.restart)
  File "/usr/local/lib/python2.7/site-packages/nodemcu_uploader/main.py", line 64, in operation_upload
    raise Exception('Error preparing nodemcu for reception')
Exception: Error preparing nodemcu for reception
jason@tolkien:~/Dropbox/projects/nodemculedchaser$ nodemcu-uploader --port /dev/tty.wchusbserial1420 --start_baud 115200 --baud 115200 upload init.lua
opening port /dev/tty.wchusbserial1420 with 115200 baud
Traceback (most recent call last):
  File "/usr/local/bin/nodemcu-uploader", line 11, in <module>
    sys.exit(main_func())
  File "/usr/local/lib/python2.7/site-packages/nodemcu_uploader/main.py", line 250, in main_func
    uploader = Uploader(args.port, args.baud, start_baud=args.start_baud)
  File "/usr/local/lib/python2.7/site-packages/nodemcu_uploader/uploader.py", line 68, in __init__
    __sync()
  File "/usr/local/lib/python2.7/site-packages/nodemcu_uploader/uploader.py", line 66, in __sync
    raise DeviceNotFoundException('Device not found or wrong port')
nodemcu_uploader.exceptions.DeviceNotFoundException: Device not found or wrong port
jason@tolkien:~/Dropbox/projects/nodemculedchaser$ nodemcu-uploader --port /dev/tty.wchusbserial1420 --start_baud 115200 --baud 115200 upload init.lua
opening port /dev/tty.wchusbserial1420 with 115200 baud
Preparing esp for transfer.
Transferring init.lua as init.lua
All done!
jason@tolkien:~/Dropbox/projects/nodemculedchaser$
```

**Comment by jasonblewis** [comment]
closing because I tested with the luatool.py and see similar erros. I'm thinking its a hardware or serial driver issue
