### ISSUE TITLE
nodemcu-uploader problem

### ISSUE THREAD

**Issue by msbrigittte** [kmpm/nodemcu-uploader#62]
when I try to use nodemcu uploader, this happends:

C:\Users\Lukasz\Desktop>pip install nodemcu-uploader
Requirement already satisfied (use --upgrade to upgrade): nodemcu-uploader in c:\python34\lib\site-packages
Requirement already satisfied (use --upgrade to upgrade): pyserial>=2.7 in c:\python34\lib\site-packages (from nodemcu-uploader)
You are using pip version 7.1.2, however version 8.1.2 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.

C:\Users\Lukasz\Desktop>nodemcu-uploader
Traceback (most recent call last):
  File "C:\Python34\Scripts\nodemcu-uploader-script.py", line 9, in <module>
    load_entry_point('nodemcu-uploader==0.3.2', 'console_scripts', 'nodemcu-uploader')()
  File "c:\python34\lib\site-packages\pkg_resources\__init__.py", line 558, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "c:\python34\lib\site-packages\pkg_resources\__init__.py", line 2682, in load_entry_point
    return ep.load()
  File "c:\python34\lib\site-packages\pkg_resources\__init__.py", line 2355, in load
    return self.resolve()
  File "c:\python34\lib\site-packages\pkg_resources\__init__.py", line 2361, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "c:\python34\lib\site-packages\nodemcu_uploader\main.py", line 76
    print 'sources', sources
                  ^
SyntaxError: Missing parentheses in call to 'print'

any ideas? wrong python? wrong windows?

**Comment by kmpm** [comment]
Looks like you have python 3, and that will sadly not work yet.

Den 25 juli 2016 11:24 fm skrev "msbrigittte" <notifications@github.com>:

**Comment by msbrigittte** [comment]
thanks :)
